import '../../../models/tool_call_models.dart';
import '../tool_handler.dart';
import '../../../agent/pipeline/pipeline_models.dart';
import '../../../agent/pipeline/pipeline_orchestrator.dart';

class PipelineTriggerTool implements ToolHandler {
  @override
  final ToolDescriptor descriptor = const ToolDescriptor(
    id: 'pipeline.trigger',
    name: 'Trigger CI Pipeline',
    description: 'Triggers active build and test stages.',
    category: ToolCategory.workspace,
    requiresPermission: false,
    readOnly: false,
    destructive: false,
    modifiesWorkspace: false,
    tags: ['pipeline', 'trigger'],
  );

  @override
  Future<ToolCallResult> execute(
      ToolCallRequest request, ToolExecutionContext context) async {
    final stopwatch = Stopwatch()..start();
    final commit = request.arguments['commitHash'] as String? ?? 'sha-latest';

    final orch = PipelineOrchestratorRegistry.active ??
        PipelineOrchestratorRegistry.get(context.workspaceId) ??
        PipelineOrchestrator();

    final run = await orch.triggerPipeline(commit);

    return ToolCallResult(
      success: true,
      output: ToolOutput(
        data: run.toJson(),
        displayText: 'Pipeline run ${run.id} triggered successfully.',
        mimeType: 'application/json',
      ),
      duration: stopwatch.elapsed,
    );
  }
}

class PipelineStatusTool implements ToolHandler {
  @override
  final ToolDescriptor descriptor = const ToolDescriptor(
    id: 'pipeline.status',
    name: 'Get Pipeline Status',
    description: 'Retrieves current status details of active pipeline runs.',
    category: ToolCategory.workspace,
    requiresPermission: false,
    readOnly: true,
    destructive: false,
    modifiesWorkspace: false,
    tags: ['pipeline', 'status'],
  );

  @override
  Future<ToolCallResult> execute(
      ToolCallRequest request, ToolExecutionContext context) async {
    final stopwatch = Stopwatch()..start();
    final runId = request.arguments['runId'] as String? ?? 'run-latest';

    final orch = PipelineOrchestratorRegistry.active ??
        PipelineOrchestratorRegistry.get(context.workspaceId) ??
        PipelineOrchestrator();

    final run = await orch.provider.getRun(runId);

    return ToolCallResult(
      success: true,
      output: ToolOutput(
        data: run.toJson(),
        displayText: 'Status loaded for run $runId.',
        mimeType: 'application/json',
      ),
      duration: stopwatch.elapsed,
    );
  }
}

class PipelineLogsTool implements ToolHandler {
  @override
  final ToolDescriptor descriptor = const ToolDescriptor(
    id: 'pipeline.logs',
    name: 'Get Pipeline Logs',
    description: 'Retrieves logs generated by pipeline run.',
    category: ToolCategory.workspace,
    requiresPermission: false,
    readOnly: true,
    destructive: false,
    modifiesWorkspace: false,
    tags: ['pipeline', 'logs'],
  );

  @override
  Future<ToolCallResult> execute(
      ToolCallRequest request, ToolExecutionContext context) async {
    final stopwatch = Stopwatch()..start();
    final runId = request.arguments['runId'] as String? ?? 'run-latest';

    final orch = PipelineOrchestratorRegistry.active ??
        PipelineOrchestratorRegistry.get(context.workspaceId) ??
        PipelineOrchestrator();

    final logsList = await orch.provider.logs(runId);

    return ToolCallResult(
      success: true,
      output: ToolOutput(
        data: {'logs': logsList.map((l) => l.toJson()).toList()},
        displayText: 'Logs loaded for run $runId.',
        mimeType: 'application/json',
      ),
      duration: stopwatch.elapsed,
    );
  }
}

class PipelineArtifactsTool implements ToolHandler {
  @override
  final ToolDescriptor descriptor = const ToolDescriptor(
    id: 'pipeline.artifacts',
    name: 'Get Pipeline Artifacts',
    description: 'Retrieves artifacts produced by pipeline run.',
    category: ToolCategory.workspace,
    requiresPermission: false,
    readOnly: true,
    destructive: false,
    modifiesWorkspace: false,
    tags: ['pipeline', 'artifacts'],
  );

  @override
  Future<ToolCallResult> execute(
      ToolCallRequest request, ToolExecutionContext context) async {
    final stopwatch = Stopwatch()..start();
    final runId = request.arguments['runId'] as String? ?? 'run-latest';

    final orch = PipelineOrchestratorRegistry.active ??
        PipelineOrchestratorRegistry.get(context.workspaceId) ??
        PipelineOrchestrator();

    final artifactsList = await orch.provider.artifacts(runId);

    return ToolCallResult(
      success: true,
      output: ToolOutput(
        data: {'artifacts': artifactsList.map((a) => a.toJson()).toList()},
        displayText: 'Artifacts loaded for run $runId.',
        mimeType: 'application/json',
      ),
      duration: stopwatch.elapsed,
    );
  }
}

class PipelineCancelTool implements ToolHandler {
  @override
  final ToolDescriptor descriptor = const ToolDescriptor(
    id: 'pipeline.cancel',
    name: 'Cancel Active Run',
    description: 'Cancels running stages of active pipeline.',
    category: ToolCategory.workspace,
    requiresPermission: false,
    readOnly: false,
    destructive: false,
    modifiesWorkspace: false,
    tags: ['pipeline', 'cancel'],
  );

  @override
  Future<ToolCallResult> execute(
      ToolCallRequest request, ToolExecutionContext context) async {
    final stopwatch = Stopwatch()..start();
    final runId = request.arguments['runId'] as String? ?? 'run-latest';

    final orch = PipelineOrchestratorRegistry.active ??
        PipelineOrchestratorRegistry.get(context.workspaceId) ??
        PipelineOrchestrator();

    await orch.provider.cancel(runId);

    return ToolCallResult(
      success: true,
      output: ToolOutput(
        displayText: 'Pipeline run $runId cancelled.',
        mimeType: 'text/plain',
      ),
      duration: stopwatch.elapsed,
    );
  }
}

class PipelineDeployTool implements ToolHandler {
  @override
  final ToolDescriptor descriptor = const ToolDescriptor(
    id: 'pipeline.deploy',
    name: 'Deploy Release package',
    description:
        'Triggers target environment deployments (Production requires approval).',
    category: ToolCategory.workspace,
    requiresPermission: false,
    readOnly: false,
    destructive: false,
    modifiesWorkspace: false,
    tags: ['pipeline', 'deploy'],
  );

  @override
  Future<ToolCallResult> execute(
      ToolCallRequest request, ToolExecutionContext context) async {
    final stopwatch = Stopwatch()..start();
    final deploymentId =
        request.arguments['deploymentId'] as String? ?? 'dep-latest';
    final targetStr = request.arguments['target'] as String? ?? 'staging';
    final approved = request.arguments['userApproved'] as bool? ?? false;

    final target = DeploymentTarget.values.firstWhere(
      (e) => e.name == targetStr,
      orElse: () => DeploymentTarget.staging,
    );

    final orch = PipelineOrchestratorRegistry.active ??
        PipelineOrchestratorRegistry.get(context.workspaceId) ??
        PipelineOrchestrator();

    final result =
        orch.runDeployment(deploymentId, target, userApproved: approved);

    return ToolCallResult(
      success: true,
      output: ToolOutput(
        data: result.toJson(),
        displayText: 'Deployment status: ${result.status.name}.',
        mimeType: 'application/json',
      ),
      duration: stopwatch.elapsed,
    );
  }
}

class PipelineRollbackTool implements ToolHandler {
  @override
  final ToolDescriptor descriptor = const ToolDescriptor(
    id: 'pipeline.rollback',
    name: 'Rollback Deployment',
    description: 'Triggers emergency rollbacks and restores stable revisions.',
    category: ToolCategory.workspace,
    requiresPermission: false,
    readOnly: false,
    destructive: true,
    modifiesWorkspace: true,
    tags: ['pipeline', 'rollback'],
  );

  @override
  Future<ToolCallResult> execute(
      ToolCallRequest request, ToolExecutionContext context) async {
    final stopwatch = Stopwatch()..start();
    final deploymentId =
        request.arguments['deploymentId'] as String? ?? 'dep-latest';
    final revision =
        request.arguments['targetRevision'] as String? ?? 'sha-stable';

    final orch = PipelineOrchestratorRegistry.active ??
        PipelineOrchestratorRegistry.get(context.workspaceId) ??
        PipelineOrchestrator();

    final plan = orch.triggerRollback(deploymentId, revision);

    return ToolCallResult(
      success: true,
      output: ToolOutput(
        data: plan.toJson(),
        displayText: 'Rollback completed to target revision $revision.',
        mimeType: 'application/json',
      ),
      duration: stopwatch.elapsed,
    );
  }
}

class PipelineSummaryTool implements ToolHandler {
  @override
  final ToolDescriptor descriptor = const ToolDescriptor(
    id: 'pipeline.summary',
    name: 'Get Pipeline Run Summary',
    description: 'Provides summary statistics of pipeline execution metrics.',
    category: ToolCategory.workspace,
    requiresPermission: false,
    readOnly: true,
    destructive: false,
    modifiesWorkspace: false,
    tags: ['pipeline', 'summary'],
  );

  @override
  Future<ToolCallResult> execute(
      ToolCallRequest request, ToolExecutionContext context) async {
    final stopwatch = Stopwatch()..start();

    final metrics = const PipelineMetrics(
      totalRuns: 10,
      successfulRuns: 9,
      successRate: 0.9,
      averageDuration: Duration(seconds: 120),
    );

    return ToolCallResult(
      success: true,
      output: ToolOutput(
        data: metrics.toJson(),
        displayText: 'Overall metrics loaded.',
        mimeType: 'application/json',
      ),
      duration: stopwatch.elapsed,
    );
  }
}
